name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release of the ${{ matrix.dir }} directory for dotnet v${{ matrix.dotnet }} on ${{ matrix.dotnet }}
    strategy:
      matrix:
          dotnet: [ '5.0.x' ]
          os: [ ubuntu-latest, windows-latest ]
          dir: [ console ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Build
      shell: bash
      run: |
        cd ${{ matrix.dir }}
        tag=$(git describe --tags --abbrev=0)
        release_name="App-$tag--${{ matrix.os }}--dotnet-V${{ os.dotnet }}--app-${{ matrix.dir }}"
        # Build everything
        dotnet publish src/App/App.csproj --framework netcoreapp3.1 --runtime "${{ matrix.os }}" -c Release -o "$release_name"
        # Pack files
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          # Pack to zip for Windows
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
        else
        tar czvf "${release_name}.tar.gz" "$release_name"
        fi
        # Delete output directory
        rm -r "$release_name"
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "App*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}