name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release of the ${{ matrix.dir }} directory for dotnet v5.0.x on ${{ matrix.os }}
    strategy:
      matrix:
        kind: ['linux', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64

        dir: [ console ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: console

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build
      shell: bash
      run: |
        tag=$(git describe --tags --abbrev=0)
        release_name="App-$tag--${{ matrix.os }}--dotnet-V${{ matrix.dotnet }}"
        # Build everything
        dotnet publish ${{ matrix.dir }}.csproj --framework netcoreapp5.0 --runtime "${{ matrix.target }}" -c Release -o "$release_name"
        # Pack files
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          # Pack to zip for Windows
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
        else
        tar czvf "${release_name}.tar.gz" "$release_name"
        fi
        # Delete output directory
        rm -r "$release_name"
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "App*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}